// urlstr-frontend-angular/src/app/about/about.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'us-about',
  templateUrl: './about.component.html',
  styleUrls: ['./about.component.css']
})
export class AboutComponent {

  constructor() { }
}

<h1>About 'URLStr'</h1>

<p><em>URLStr</em> is short for <em>URLStore</em> and is a little
  bookmark management application using an embedded <a href="https://neo4j.com/">Neo4J</a>
  database in the background for rich data management, <a href="https://quarkus.io/">Quarkus</a>
  using Java as backend framework, and <a href="https://angular.io/">Angular</a> for the frontend.</p>

<p>URLStr was created because of my need to manage, tag, comment and query my huge list of
  online resources.
</p>

<p>Another need was to have my bookmarks stored in a <em>local</em> application that runs
  in my home network. In fact it should run on my NAS as a simple docker container - easy to
  setup.</p>

<p>The most import and final need was to experiment with (for me) new technology, in this
  case above mentioned Quarkus, Neo4J and Angular.</p>

// urlstr-frontend-svelte/src/routes/about.svelte
<svelte:head>
	<title>About</title>
</svelte:head>

<h1>About 'URLStr'</h1>

<p><em>URLStr</em> is short for <em>URLStore</em> and is a little
bookmark management application using an embedded <a href="https://neo4j.com/">Neo4J</a>
database in the background for rich data management, <a href="https://quarkus.io/">Quarkus</a>
using Java as backend framework, and <a href="https://svelte.dev/">Svelte</a> for the frontend.</p>

<p>URLStr was created because of my need to manage, tag, comment and query my huge list of
online resources.
</p>

<p>Another need was to have my bookmarks stored in a <em>local</em> application that runs
in my home network. In fact it should run on my NAS as a simple docker container - easy to
setup.</p>

<p>The most import and final need was to experiment with (for me) new technology, in this
case above mentioned Quarkus, Neo4J and Svelte.</p>
